name: Octopus MinMax Tariff Bot

on:
  # Schedule the live run to trigger every day at 11 PM London time.
  # Note: GitHub Actions cron schedules run on UTC. 23:00 UTC is 11 PM GMT (winter) 
  # or midnight BST (summer). The TZ="Europe/London" inside the container handles the
  # time correctly, but the trigger is based on UTC.
  schedule:
    - cron: '0 23 * * *'

  # Allows you to manually run the workflow from the Actions tab for dry runs.
  workflow_dispatch:

jobs:
  # JOB 1: A safe dry run to test the bot's calculations.
  # This job will ONLY run when you trigger it manually.
  dry-run:
    name: Dry Run Tariff Check (Manual)
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Run Octopus MinMax Bot in Dry Run Mode
        run: |
          echo "🚀 Starting Octopus MinMax Bot in DRY RUN mode..."
          docker run \
            --name MinMaxBot-DryRun \
            -e ACC_NUMBER="${{ secrets.ACC_NUMBER }}" \
            -e API_KEY="${{ secrets.API_KEY }}" \
            -e NOTIFICATION_URLS="${{ secrets.NOTIFICATION_URLS }}" \
            -e TARIFFS="agile,cosy,go,tracker" \
            -e TZ="Europe/London" \
            -e BATCH_NOTIFICATIONS=false \
            -e ONE_OFF=true \
            -e DRY_RUN=true \
            eelmafia/octopus-minmax-bot

  # JOB 2: The live run that performs the actual switch.
  # This job will ONLY run at the scheduled time (11 PM).
  live-run:
    name: Live Tariff Switch (Scheduled at 11 PM)
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Run Octopus MinMax Bot in Live Mode
        run: |
          echo "🔴 Starting Octopus MinMax Bot in LIVE mode..."
          docker run \
            --name MinMaxBot-Live \
            -e ACC_NUMBER="${{ secrets.ACC_NUMBER }}" \
            -e API_KEY="${{ secrets.API_KEY }}" \
            -e NOTIFICATION_URLS="${{ secrets.NOTIFICATION_URLS }}" \
            -e TARIFFS="agile,cosy,go,tracker" \
            -e TZ="Europe/London" \
            -e BATCH_NOTIFICATIONS=false \
            -e ONE_OFF=true \
            -e DRY_RUN=false \
            eelmafia/octopus-minmax-bot
