name: Octopus MinMax Bot (11 PM BST Auto + Manual Dry Run)

on:
  schedule:
    # Automatic live run at 11 PM London time (handles BST/GMT automatically)
    - cron: '0 22,23 * * *'  # Covers both BST (22:00 UTC) and GMT (23:00 UTC)
  
  # Manual dry run option available anytime
  workflow_dispatch:

jobs:
  # Automatic live run at 11 PM
  scheduled-live-run:
    name: Automatic Live Run (11 PM BST)
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Check if it's 11 PM London time
        id: time-check
        run: |
          current_hour=$(TZ='Europe/London' date +'%H')
          if [[ "$current_hour" == "23" ]]; then
            echo "It's 11 PM London time - running live bot"
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "Not 11 PM London time - skipping"
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

      - name: Run live tariff switching bot
        if: steps.time-check.outputs.should_run == 'true'
        run: |
          echo "🔴 Running LIVE tariff switching at 11 PM BST..."
          docker run \
            --name MinMaxBot-Live \
            -e ACC_NUMBER="${{ secrets.ACC_NUMBER }}" \
            -e API_KEY="${{ secrets.API_KEY }}" \
            -e NOTIFICATION_URLS="${{ secrets.NOTIFICATION_URLS }}" \
            -e TARIFFS="agile,cosy,go" \
            -e TZ="Europe/London" \
            -e BATCH_NOTIFICATIONS=false \
            -e ONE_OFF=true \
            -e DRY_RUN=false \
            eelmafia/octopus-minmax-bot

  # Manual dry run (available anytime)
  manual-dry-run:
    name: Manual Dry Run Check
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Run dry run for cost comparison
        run: |
          echo "🚀 Running manual dry run for cost comparison..."
          docker run \
            --name MinMaxBot-DryRun \
            -e ACC_NUMBER="${{ secrets.ACC_NUMBER }}" \
            -e API_KEY="${{ secrets.API_KEY }}" \
            -e NOTIFICATION_URLS="${{ secrets.NOTIFICATION_URLS }}" \
            -e TARIFFS="agile,cosy,go" \
            -e TZ="Europe/London" \
            -e BATCH_NOTIFICATIONS=false \
            -e ONE_OFF=true \
            -e DRY_RUN=true \
            eelmafia/octopus-minmax-bot
