name: Octopus MinMax Bot (Manual & Scheduled)

on:
  schedule:
    - cron: '0 22 * * *' # 10 PM Dry Run
    - cron: '0 23 * * *' # 11 PM Live Run

  # This section enables and configures the manual trigger
  workflow_dispatch:
    inputs:
      run_type:
        description: 'Which job to run manually?'
        required: true
        type: choice
        options:
        - dry-run # The 10 PM notification logic
        - live-run # The 11 PM switch logic
        default: 'dry-run'

jobs:
  # This job handles BOTH the 10 PM scheduled run AND any manual dry runs
  dry-run:
    name: Dry Run Tariff Check
    runs-on: ubuntu-latest
    # The 'if' condition now checks for either of the two triggers
    if: (github.event_name == 'schedule' && github.event.schedule == '0 22 * * *') || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_type == 'dry-run')
    steps:
      - name: Run bot in notification-only dry run mode
        run: |
          echo "🚀 Running Dry Run (Notification Mode)..."
          docker run \
            --name MinMaxBot-DryRun \
            -e ACC_NUMBER="${{ secrets.ACC_NUMBER }}" \
            -e API_KEY="${{ secrets.API_KEY }}" \
            -e NOTIFICATION_URLS="${{ secrets.NOTIFICATION_URLS }}" \
            -e TARIFFS="agile,cosy,go,tracker" \
            -e TZ="Europe/London" \
            -e BATCH_NOTIFICATIONS=false \
            -e ONE_OFF=true \
            -e DRY_RUN=true \
            eelmafia/octopus-minmax-bot

  # This job handles the 11 PM scheduled run AND any manual live runs
  live-switch:
    name: Live Tariff Switch
    runs-on: ubuntu-latest
    if: (github.event_name == 'schedule' && github.event.schedule == '0 23 * * *') || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_type == 'live-run')
    steps:
      - name: Run bot in live switch mode
        run: |
          echo "🔴 Running Live Switch Mode..."
          docker run \
            --name MinMaxBot-Live \
            -e ACC_NUMBER="${{ secrets.ACC_NUMBER }}" \
            -e API_KEY="${{ secrets.API_KEY }}" \
            -e NOTIFICATION_URLS="${{ secrets.NOTIFICATION_URLS }}" \
            -e TARIFFS="agile,cosy,go,tracker" \
            -e TZ="Europe/London" \
            -e BATCH_NOTIFICATIONS=false \
            -e ONE_OFF=true \
            -e DRY_RUN=false \
            eelmafia/octopus-minmax-bot
